#!/usr/bin/env python3
"""Render thin assistant adapters for portable-jira-flow."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path


SKILL_NAME = "portable-jira-flow"
MARKER = "Generated by portable-jira-flow installer."
TARGETS = {
    "codex": Path.home() / ".codex" / "skills" / SKILL_NAME,
    "claude": Path.home() / ".claude" / "skills" / SKILL_NAME,
    "cursor": Path.home() / ".cursor" / "skills" / SKILL_NAME,
}


def parse_targets(raw: str) -> list[str]:
    if raw == "all":
        return list(TARGETS)
    targets = [item.strip() for item in raw.split(",") if item.strip()]
    unknown = sorted(set(targets) - set(TARGETS))
    if unknown:
        raise SystemExit(f"Unknown target(s): {', '.join(unknown)}")
    return targets


def render_template(template: Path, skill_root: Path) -> str:
    content = template.read_text(encoding="utf-8")
    return content.replace("{{SKILL_ROOT}}", str(skill_root))


def write_adapter(target: str, destination: Path, content: str, dry_run: bool, force: bool) -> None:
    skill_file = destination / "SKILL.md"
    if dry_run:
        print(f"[dry-run] {target}: would write {skill_file}")
        return

    if skill_file.exists():
        existing = skill_file.read_text(encoding="utf-8", errors="replace")
        if MARKER not in existing and not force:
            raise SystemExit(
                f"{skill_file} exists and does not look generated. "
                "Use --force to overwrite intentionally."
            )

    destination.mkdir(parents=True, exist_ok=True)
    skill_file.write_text(content, encoding="utf-8")


def copy_openai_metadata(skill_root: Path, destination: Path, dry_run: bool) -> None:
    source = skill_root / "agents" / "openai.yaml"
    if not source.exists():
        return

    dest = destination / "agents" / "openai.yaml"
    if dry_run:
        print(f"[dry-run] codex: would write {dest}")
        return

    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, dest)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--targets", default="all", help="Comma-separated targets: codex,claude,cursor or all.")
    parser.add_argument("--skill-root", default=None, help="Canonical skill root. Defaults to this script's parent skill.")
    parser.add_argument("--dry-run", action="store_true", help="Show writes without changing files.")
    parser.add_argument("--force", action="store_true", help="Overwrite non-generated adapter SKILL.md files.")
    args = parser.parse_args(argv)

    skill_root = Path(args.skill_root).expanduser().resolve() if args.skill_root else Path(__file__).resolve().parents[1]
    templates = skill_root / "adapters" / "templates"
    if not (skill_root / "SKILL.md").exists():
        raise SystemExit(f"Missing canonical skill at {skill_root / 'SKILL.md'}")

    for target in parse_targets(args.targets):
        template = templates / f"{target}.SKILL.md.tmpl"
        if not template.exists():
            raise SystemExit(f"Missing adapter template: {template}")
        destination = TARGETS[target]
        write_adapter(target, destination, render_template(template, skill_root), args.dry_run, args.force)
        if target == "codex":
            copy_openai_metadata(skill_root, destination, args.dry_run)
        if not args.dry_run:
            print(f"[OK] {target}: installed {destination}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
